#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : require
#include "../common.glsl"

struct RayCastQuery {
    vec3 direction;
    float tmin;
    vec3 position;
    float tmax;
};

struct Payload {
  uint inInstanceIndex; 
};

layout(location = 0) rayPayloadEXT Payload payload;

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;

layout(set = 1, binding = 0) readonly buffer RayCastQueryBuffer {
    RayCastQuery queries[];
};

layout(set = 1, binding = 1) writeonly buffer RayCastResultBuffer {
    uint results[];
};

void main() {
    RayCastQuery query = queries[gl_LaunchIDEXT.x];
    traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0,
        query.position,
        query.tmin,
        query.direction,
        query.tmax, 0);
}
