#version 450
layout(local_size_x = 16, local_size_y = 16) in;

#extension GL_GOOGLE_include_directive : require
#extension GL_NV_compute_shader_derivatives : require
#include "common.glsl"

layout(set = 0, binding = 0, rgba16) uniform image2D mainImage;
layout(set = 0, binding = 1, rgba16) readonly uniform image2D mrNormalImage;
layout(set = 0, binding = 2, r32f) readonly uniform image2D depthImage;
layout(set = 0, binding = 3) uniform sampler2D noiseImage;

const uint KERNEL_SIZE = 32;
layout(set = 0, binding = 4) readonly buffer KernelSamples {
    vec3 samples[KERNEL_SIZE];
};

layout(set = 1, binding = 0) uniform CameraUBO {
    Camera camera;
};

vec3 PositionFromDepth(float depth, vec2 uv) {
    vec3 ndc = vec3(uv * 2.0 - 1.0, 1.0 - depth);

    vec4 clipSpacePosition = vec4(ndc, 1.0);
    vec4 viewSpacePosition = camera.invProj * clipSpacePosition;
    viewSpacePosition /= viewSpacePosition.w;

    return viewSpacePosition.xyz;
}

vec3 CalculateNormal(vec2 N) {
    vec3 n = vec3(N.x, N.y, 1.0 - abs(N.x) - abs(N.y));
    float t = clamp(-n.z, 0.0, 1.0);
    n.xy += (n.x >= 0.0 ? -t : t) * (n.y >= 0.0 ? 1.0 : -1.0);
    return normalize(n);
}

const float PI = 3.14159265359;
const float RADIUS = 1.5;
const float BIAS = 0.025;

const vec2 noiseScale = vec2(1600 / 4.0, 900 / 4.0);

void main() {
    uvec2 imageExtent = imageSize(mainImage); // / uvec2(2, 1);

    if (gl_GlobalInvocationID.x >= imageExtent.x || gl_GlobalInvocationID.y >= imageExtent.y) {
        return;
    }

    vec2 pixelCenter = vec2(gl_GlobalInvocationID.xy) + vec2(0.5);
    vec2 centerUV = pixelCenter / vec2(imageExtent);

    vec4 color = imageLoad(mainImage, ivec2(gl_GlobalInvocationID.xy));
    float depth = imageLoad(depthImage, ivec2(gl_GlobalInvocationID.xy)).r;
    vec2 storedNormal = imageLoad(mrNormalImage, ivec2(gl_GlobalInvocationID.xy)).zw;
    vec3 normal = CalculateNormal(storedNormal);
    vec3 viewPos = PositionFromDepth(depth, centerUV);

    vec3 randomVec = texture(noiseImage, centerUV * noiseScale).rgb;

    vec3 tangent = normalize(randomVec - normal * dot(normal, randomVec));
    if (length(tangent) < 1e-3) tangent = normalize(cross(normal, vec3(0.0, 0.0, 1.0)));
    vec3 bitangent = normalize(cross(normal, tangent));
    mat3 TBN = mat3(tangent, bitangent, normal);

    float ao = 0.0;

    for (uint i = 0; i < KERNEL_SIZE; ++i) {
        vec3 samplePos = TBN * samples[i];
        samplePos = viewPos + samplePos * RADIUS;

        vec4 offset = vec4(samplePos, 1.0);
        offset = camera.projection * offset;
        offset.xyz /= offset.w;
        offset.xyz = offset.xyz * 0.5 + 0.5;
        float sampleDepth = imageLoad(depthImage, ivec2(offset.xy * vec2(imageExtent))).r;
        vec3 offsetPos = PositionFromDepth(sampleDepth, offset.xy);

        float rangeCheck = smoothstep(0.0, 1.0, RADIUS / abs(viewPos.z - offsetPos.z));
        if (samplePos.z + BIAS <= offsetPos.z) ao += 1.0 * rangeCheck;
    }

    ao /= float(KERNEL_SIZE);
    ao = 1.0 - ao;

    imageStore(mainImage, ivec2(gl_GlobalInvocationID.xy), vec4(vec3(color.rgb * ao), 1.0));
}
