#version 450
layout(local_size_x = 64) in;

#extension GL_EXT_buffer_reference : require
#extension GL_GOOGLE_include_directive : require
#include "common.glsl"

layout(set = 0, binding = 0) buffer DrawCommands {
    DrawIndexedIndirectCommand drawCommands[];
};

layout(set = 0, binding = 1) buffer DrawCount {
    uint drawCount;
};

layout(set = 0, binding = 2) buffer VisibleInstances {
    uint visibleInstances[];
};

layout(set = 1, binding = 0) uniform CameraUBO {
    Camera camera;
};

layout(set = 2, binding = 0) readonly buffer Instances {
    Instance instances[];
};

layout(set = 3, binding = 1) readonly buffer GpuMeshes {
    GpuMesh gpuMeshes[];
};

layout(set = 3, binding = 2) readonly buffer SphereBoundsBuffer {
    SphereBounds sphereBounds[];
};

bool isBoundingSphereVisible(mat4 viewProj, vec3 center, float radius);

void main() {
    uint id = gl_GlobalInvocationID.x;

    if (id == 0) {
        drawCount = 0;
    }

    Instance instance = instances[id];

    if (instance.matrix == mat4(0.0)) {
        return;
    }

    mat4 viewProj = camera.projection * camera.view;

    uint objectId = instance.objectIndex;

    if (isBoundingSphereVisible(viewProj, sphereBounds[objectId].center, sphereBounds[objectId].radius)) {
        uint index = atomicAdd(drawCount, 1);
        visibleInstances[index] = id;
        DrawIndexedIndirectCommand command;
        command.indexCount = gpuMeshes[objectId].indexCount;
        command.instanceCount = 1;
        command.firstIndex = 0;
        command.vertexOffset = 0;
        command.firstInstance = index;
        drawCommands[index] = command;
    }
}

bool isBoundingSphereVisible(mat4 viewProj, vec3 center, float radius) {
    vec4 clip = viewProj * vec4(center, 1.0);

    if (clip.z + radius < 0.0) return false;

    float r = radius;

    return !(abs(clip.x) <= clip.w + r &&
        abs(clip.y) <= clip.w + r &&
        clip.z - r >= 0.0 &&
        clip.z + r <= clip.w);
}
