#version 450
layout(local_size_x = 64) in;

#extension GL_EXT_buffer_reference : require
#extension GL_GOOGLE_include_directive : require
#include "common.glsl"

layout(set = 0, binding = 0) buffer DrawCommands {
    DrawIndexedIndirectCommand drawCommands[];
};

layout(set = 0, binding = 1) buffer DrawCount {
    uint drawCount;
};

layout(set = 0, binding = 2) buffer VisibleInstances {
    uint visibleInstances[];
};

layout(set = 1, binding = 0) uniform CameraUBO {
    Camera camera;
};

layout(set = 2, binding = 0) readonly buffer Instances {
    Instance instances[];
};

layout(set = 3, binding = 1) readonly buffer GpuMeshes {
    GpuMesh gpuMeshes[];
};

layout(set = 3, binding = 2) readonly buffer AABBs {
    AABB aabbs[];
};

bool isAABBVisible(AABB box, mat4 viewProj);

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id == 0) {
        drawCount = 0;
    }
    if (aabbs[id].min == vec3(0.0) && aabbs[id].max == vec3(0.0)) {
        return;
    }

    mat4 viewProj = camera.projection * camera.view;

    if (isAABBVisible(aabbs[id], viewProj)) {
        uint index = atomicAdd(drawCount, 1);
        visibleInstances[index] = id;
        DrawIndexedIndirectCommand command;
        command.indexCount = gpuMeshes[id].indexCount;
        command.instanceCount = 1;
        command.firstIndex = 0;
        command.vertexOffset = 0;
        command.firstInstance = 0;
        drawCommands[index] = command;
    }
}

bool isAABBVisible(AABB box, mat4 viewProj) {
    vec3 corners[8];
    corners[0] = vec3(box.min.x, box.min.y, box.min.z);
    corners[1] = vec3(box.max.x, box.min.y, box.min.z);
    corners[2] = vec3(box.min.x, box.max.y, box.min.z);
    corners[3] = vec3(box.max.x, box.max.y, box.min.z);
    corners[4] = vec3(box.min.x, box.min.y, box.max.z);
    corners[5] = vec3(box.max.x, box.min.y, box.max.z);
    corners[6] = vec3(box.min.x, box.max.y, box.max.z);
    corners[7] = vec3(box.max.x, box.max.y, box.max.z);

    bool allOutside = true;
    for (int i = 0; i < 8; ++i) {
        vec4 clip = viewProj * vec4(corners[i], 1.0);
        if (abs(clip.x) <= clip.w &&
                abs(clip.y) <= clip.w &&
                0.0 <= clip.z && clip.z <= clip.w)
            allOutside = false;
    }

    return !allOutside;
}
