#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#include "common.glsl"

struct RayQuery {
    vec3 origin;
    float tMin;
    vec3 direction;
    float tMax;
};

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;

layout(set = 1, binding = 0) readonly buffer RayQueries {
    RayQuery rayQueries[];
};

layout(set = 1, binding = 1) writeonly buffer RayHits {
    uint rayHits[];
};

layout(location = 0) rayPayloadEXT uint hitInstanceIndex;

void main() {
    /*
                                            const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
                                            const vec2 inUV = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
                                            vec4 ndc = vec4(inUV * 2.0 - 1.0, 0, 1);
                                            vec4 target = camera.invProj * vec4(ndc);
                                            vec4 direction = camera.invView * vec4(target.xyz, 0);
                                            */
    RayQuery rayQuery = rayQueries[gl_LaunchIDEXT.x];

    traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0,
        rayQuery.origin.xyz, rayQuery.tMin, rayQuery.direction.xyz, rayQuery.tMax, 0);

    rayHits[gl_LaunchIDEXT.x] = hitInstanceIndex;
}
