#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#include "common.glsl"

struct RayQuery {
    vec3 origin;
    float tMin;
    vec3 direction;
    float tMax;
};

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;

layout(set = 1, binding = 0) readonly buffer RayQueries {
    RayQuery rayQueries[];
};

layout(set = 1, binding = 1) writeonly buffer RayHits {
    uint rayHits[];
};

layout(location = 0) rayPayloadEXT uint hitInstanceIndex;

void main() {
    RayQuery rayQuery = rayQueries[gl_LaunchIDEXT.x];

    traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0,
        rayQuery.origin.xyz, rayQuery.tMin, rayQuery.direction.xyz, rayQuery.tMax, 0);

    rayHits[gl_LaunchIDEXT.x] = hitInstanceIndex;
}
