#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : require
#include "common.glsl"

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1, rgba16) uniform image2D mainImage;
layout(set = 0, binding = 2, rgba16) uniform image2D mrNormalImage;
layout(set = 0, binding = 3, r32f) readonly uniform image2D depthImage;

layout(set = 1, binding = 0) uniform CameraUBO {
    Camera camera;
};

struct Payload {
    vec3 inColor;
    vec3 outWorldPosition;
};

layout(location = 0) rayPayloadEXT Payload payload;

vec3 PositionFromDepth(float depth, vec2 uv) {
    vec3 ndc = vec3(uv * 2.0 - 1.0, 1.0 - depth);

    vec4 clipSpacePosition = vec4(ndc, 1.0);
    vec4 viewSpacePosition = camera.invProj * clipSpacePosition;
    viewSpacePosition /= viewSpacePosition.w;
    vec4 worldSpacePosition = camera.invView * viewSpacePosition;

    return worldSpacePosition.xyz;
}

vec3 FresnelSchlickRoughness(float cosTheta, vec3 F0, float roughness) {
    return F0 + (max(vec3(1.0 - roughness), F0) - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}

void main() {
    vec4 mrNormals = imageLoad(mrNormalImage, ivec2(gl_LaunchIDEXT.xy));
    float metallic = mrNormals.x;
    float roughness = mrNormals.y;

    if (roughness > 0.5 || metallic > 0.1) return;

    vec4 pixelColor = imageLoad(mainImage, ivec2(gl_LaunchIDEXT.xy));
    float depth = imageLoad(depthImage, ivec2(gl_LaunchIDEXT.xy)).r;
    vec3 normal = OctDecodeNormal(mrNormals.zw);

    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter / vec2(gl_LaunchSizeEXT.xy);

    vec3 position = PositionFromDepth(depth, inUV);

    payload.outWorldPosition = position;

    position = mix(position, camera.viewPos, .01); // stop artifacts

    vec4 ndc = vec4(inUV * 2.0 - 1.0, 0, 1);

    vec4 target = camera.invProj * vec4(ndc);
    vec4 direction = camera.invView * vec4(target.xyz, 0);

    vec3 reflectedDirection = reflect(normalize(direction.xyz), normal);

    float tmin = 0.001;
    float tmax = 10000.0;

    traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0,
        position,
        tmin,
        reflectedDirection.xyz, tmax, 0);

    vec3 F0 = mix(vec3(0.04), pixelColor.xyz, metallic);
    vec3 F = FresnelSchlickRoughness(dot(normal, direction.xyz), F0, roughness);

    vec3 kS = F;
    vec3 kD = (1.0 - kS) * (1.0 - metallic);
    vec3 color = kD * pixelColor.xyz + kS * payload.inColor;

    imageStore(mainImage, ivec2(gl_LaunchIDEXT.xy), vec4(color, 1.0));
}
