#version 450
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#include "common.glsl"
layout(local_size_x = 16, local_size_y = 16, local_size_z = 3) in;

layout(set = 0, binding = 0) uniform writeonly imageCube skyboxImage;

layout(set = 1, binding = 1) readonly buffer DirectionalLightBuffer {
    DirectionalLight directionalLight;
};

const vec3 BETA_MEI = vec3(.005, .013, .05);
const vec3 BETA_RAYLEIGH = vec3(.021);

const float PI = 3.14159265359;

float CalculateRayleigh(float cosTheta) {
    return (3.0 / (16.0 * PI)) * (1.0 + cosTheta * cosTheta);
}

const float G = 0.8;
const float G2 = G * G;

float CalculateMei(float cosTheta) {
    float denom = pow(1.0 + G2 - 2.0 * G * cosTheta, 1.5);
    const float coefficient = 3.0 / (8.0 * PI);
    float numerator = 1.0 - G2;
    return coefficient * (numerator / ((2.0 + G2) * denom));
}

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    uint cubeFace = gl_GlobalInvocationID.z;

    ivec2 faceSize = imageSize(skyboxImage);

    if (any(greaterThanEqual(coord, faceSize))) {
        return;
    }

    vec2 uv = ((vec2(coord) + vec2(0.5)) / vec2(faceSize)) * 2.0 - 1.0;
    vec3 viewDir;

    switch (cubeFace) {
        case 0:
        viewDir = normalize(vec3(1.0, -uv.y, -uv.x));
        break; // +X
        case 1:
        viewDir = normalize(vec3(-1.0, -uv.y, uv.x));
        break; // -X
        case 2:
        viewDir = normalize(vec3(uv.x, 1.0, uv.y));
        break; // +Y
        case 3:
        viewDir = normalize(vec3(uv.x, -1.0, -uv.y));
        break; // -Y
        case 4:
        viewDir = normalize(vec3(uv.x, -uv.y, 1.0));
        break; // +Z
        case 5:
        viewDir = normalize(vec3(-uv.x, -uv.y, -1.0));
        break; // -Z
        default:
        return;
    }

    float cosTheta = dot(-directionalLight.direction, viewDir);
    float pr = CalculateRayleigh(cosTheta);
    float pm = CalculateMei(cosTheta);

    vec3 sunColor = directionalLight.color * directionalLight.intensity;

    vec3 rColor = pr * BETA_RAYLEIGH * sunColor;
    vec3 mColor = pm * BETA_MEI * sunColor;

    vec3 finalColor = (rColor + mColor) * 6.0;

    imageStore(skyboxImage, ivec3(coord, cubeFace), vec4(vec3(finalColor), 1.0));
}
