#version 450
layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0, rgba16) uniform image2D mainImage;
layout(set = 0, binding = 4) uniform sampler2D aoImage;

const uint SCALE = 2;
const float INV_SCALE = 1.0 / SCALE;

void main() {
    vec2 mainImageExtent = imageSize(mainImage);
    vec2 aoImageExtent = mainImageExtent * INV_SCALE;

    if (gl_GlobalInvocationID.x >= aoImageExtent.x || gl_GlobalInvocationID.y >= aoImageExtent.y) {
        return;
    }

    vec2 invInputImageExtent = 1.0 / aoImageExtent;

    vec2 inputUV = vec2(gl_GlobalInvocationID.xy) * invInputImageExtent;
    vec4 inputValue = texture(aoImage, inputUV);

    vec2 uvStep = vec2(SCALE) * invInputImageExtent;

    for (int i = 0; i < SCALE; ++i) {
        for (int j = 0; j < SCALE; ++j) {
            float ao = texture(aoImage, inputUV + (uvStep * vec2(i, j))).r;
            vec4 color = imageLoad(mainImage, ivec2(gl_GlobalInvocationID.xy * SCALE) + ivec2(i, j));
            imageStore(mainImage, ivec2(gl_GlobalInvocationID.xy * SCALE) + ivec2(i, j), color * ao);
        }
    }
}
