#version 450
layout(local_size_x = 64) in;
#extension GL_GOOGLE_include_directive : require
#include "../common.glsl"

layout(set = 0, binding = 0) buffer DrawBuffer {
    DrawIndexedIndirectCommand drawCommands[];
};

layout(set = 0, binding = 1) buffer DrawCountBuffer {
    uint drawCount;
};

layout(set = 1, binding = 0) readonly buffer Instances {
    Instance instances[];
};

layout(set = 2, binding = 1) readonly buffer GpuMeshes {
    GpuMesh gpuMeshes[];
};

void main() {
    uint id = gl_GlobalInvocationID.x;

    if (id == 0) {
        drawCount = 0;
    }

    barrier();

    Instance instance = instances[id];

    mat4 instanceMatrix = GetInstanceMatrix(instance);

    if (instanceMatrix == Mat3x4toMat4(mat3x4(0.0))) return;

    uint objectId = GetObjectIndex(instance);

    uint index = atomicAdd(drawCount, 1);

    DrawIndexedIndirectCommand command;
    command.indexCount = gpuMeshes[objectId].indexCount;
    command.instanceCount = 1;
    command.firstIndex = gpuMeshes[objectId].firstIndex;
    command.vertexOffset = 0;
    command.firstInstance = id;

    drawCommands[index] = command;
}
